# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: axiora-api
# app and org for use with dashboard.serverless.com
app: axiora
org: ricardocamacho21

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'
useDotenv: true

custom:
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: 8080
  dynamodb:
    axioraTable: ${self:service}-${opt:stage}

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:Query'
            - 'dynamodb:GetItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
          Resource:
            - arn:aws:dynamodb:us-east-2:571994632048:table/${self:custom.dynamodb.axioraTable}
            - arn:aws:dynamodb:us-east-2:571994632048:table/${self:custom.dynamodb.axioraTable}/index/SK-PK-index

  environment:
    STAGE: ${env:STAGE}
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
    MELI_CLIENT_ID: ${env:MELI_CLIENT_ID}
    MELI_CLIENT_SECRET: ${env:MELI_CLIENT_SECRET}
    DYNAMODB_AXIORA_TABLE: ${self:custom.dynamodb.axioraTable}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
  receiveNotification:
    handler: notification.handler
  processNotification:
    handler: process-notification.handler

stepFunctions:
  stateMachines:
    notificationStepFunction:
      events:
        - http:
            path: notification/{channel}
            method: post
            request:
              template: lambda_proxy
              parameters:
                paths:
                  channel: true
      definition:
        Comment: 'Notification step function'
        StartAt: ReceiveNotification
        States:
          ReceiveNotification:
            Type: Task
            Resource: 'arn:aws:lambda:us-east-2:571994632048:function:${self:service}-${opt:stage}-receiveNotification'
            Next: ProcessNotification
          ProcessNotification:
            Type: Task
            Resource: 'arn:aws:lambda:us-east-2:571994632048:function:${self:service}-${opt:stage}-processNotification'
            End: true

resources:
  Resources:
    axioraTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamodb.axioraTable}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: SK-PK-index
            KeySchema:
              - AttributeName: SK
                KeyType: HASH
              - AttributeName: PK
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-offline
  - serverless-step-functions
